In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[1,2,3]])

b = np.array([[1,2],[1,2],[1,2]])

a @ b

array([[ 6, 12],
       [ 6, 12]])

In [3]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

j = np.concatenate((x,y),axis=1)
l = np.concatenate((x,y),axis=0)
print(j)
print(l)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
