In [1]:
import numpy as np

Matrix Multiplication

In [ ]:
a = np.array([[1,2,3],
              [1,2,3]])

b = np.array([[1,2],
              [1,2],
              [1,2]])


print(f'array{a @ b}')

#or :

np.dot(a,b)

array[[ 6 12]
 [ 6 12]]


array([[ 6, 12],
       [ 6, 12]])

Matrix Summation

In [31]:
# summed = a + b --> should have same shapes

# print(summed)

total = np.sum(a) #-> All elements of a
print(total)

col_sum = np.sum(a,axis=0) # sum of columns
print(col_sum)

row_sum = np.sum(a,axis=1) # sum of rows
print(row_sum)

12
[2 4 6]
[6 6]


Matrix Transpose

In [ ]:
A_T = a . T # -> .T is transposer
A_T

array([[1, 1],
       [2, 2],
       [3, 3]])

Identity Matrix

In [21]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

Inverse Matrix

In [ ]:
S = np.array([[1,2],[3,4]])
S_inv = np.linalg.inv(S) # -> matrix should be sqare and has 0 in result of determinant
print(S)
S_inv

[[1 2]
 [3 4]]


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Symmetric Functions

In [26]:
is_symmetric = np.allclose(S, S.T)
is_symmetric

False

Scaling A Matrix

In [29]:
λ = 3
C = S * λ
C

array([[ 3,  6],
       [ 9, 12]])

Matrix Concatenation

In [3]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

j = np.concatenate((x,y),axis=1)
l = np.concatenate((x,y),axis=0)
print(j)
print(l)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Hell Are 3D Matrixes?

In [4]:
f = np.array([[[1,2,3],[1,2,3],[1,2,3]],
              [[1,2,3],[1,2,3],[1,2,3]],
              [[1,2,3],[1,2,3],[1,2,3]]])

e = np.array([[[1,2,3],[1,2,3],[1,2,3]],
              [[1,2,3],[1,2,3],[1,2,3]],
              [[1,2,3],[1,2,3],[1,2,3]]])

f @ e

array([[[ 6, 12, 18],
        [ 6, 12, 18],
        [ 6, 12, 18]],

       [[ 6, 12, 18],
        [ 6, 12, 18],
        [ 6, 12, 18]],

       [[ 6, 12, 18],
        [ 6, 12, 18],
        [ 6, 12, 18]]])

Second Page of Notes :

In [10]:
array1 = np.array([[1,4],[7,3]])
array2 = np.array([[3,7,2],[1,6,5]])

print(array1 @ array2)


[[ 7 31 22]
 [24 67 29]]
